#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases

# OS specific

if [[ "$OSTYPE" == darwin* ]]; then
  # OS X-specific aliases
  alias find="$BREW_PREFIX/bin/gfind"
  alias xargs="$BREW_PREFIX/bin/gxargs"

  PG_DIR="$BREW_PREFIX/var/postgres"
  alias pg_start="pg_ctl -D $PG_DIR -l $PG_DIR/server.log start"
  alias pg_stop="pg_ctl -D $PG_DIR stop -s -m fast"
fi

# Python

fpath=(${ZDOTDIR:-$HOME}/.zprezto/modules/python/functions $fpath)
autoload -Uz python-info

function pyclean() {
    ZSH_PYCLEAN_PLACES=${*:-'.'}
    find ${ZSH_PYCLEAN_PLACES} -type f -name "*.py[co]" -delete
    find ${ZSH_PYCLEAN_PLACES} -type d -name "__pycache__" -delete
}

export PIP_REQUIRE_VIRTUALENV=true
export PIP_RESPECT_VIRTUALENV=true

if (( $+commands[virtualenvwrapper.sh] )); then
  export WORKON_HOME="$HOME/.virtualenvs"
  VIRTUAL_ENV_DISABLE_PROMPT=1
  source "$commands[virtualenvwrapper.sh]"
  alias wo="workon"
fi

# npm

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  source "$HOME/.nvm/nvm.sh"
fi

# Load local zshrc

if [[ -s "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi
